{
 "title": "Duty",
 "description": "Duty dashboard for prod resources - CloudWatch",
 "tags": [
  "CloudWatch",
  "AWS"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cwsource", "query": "default" },
   { "name": "instance_id", "query": "i-0d0d08e7b4a9398ce" },
   { "name": "rds_id", "query": "production" },
   { "name": "redis_0001_001", "query": "prod-cluster-0001-001" },
   { "name": "redis_0002_001", "query": "prod-cluster-0002-001" },
   { "name": "redis_0003_001", "query": "prod-cluster-0003-001" },
   { "name": "redis_0004_001", "query": "prod-cluster-0004-001" },
   { "name": "redis_all", "query": "*" },
   { "name": "nginx_access", "query": "AccessLogsToOpenSearch_logs" },
   { "name": "nginx_error", "query": "ErrorLogsToOpenSearch_logs" },
   { "name": "cwl", "query": "LogsToElasticsearch_logs" }
  ]
 },
 "panels": [
  { "title": "PROD monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EC2 PROD",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "c5.9xlarge - CPU: **36**, Memory: **72GB**, Network: **10Gbit/s**, EBS: **9.5Gbit/s**"
   }
  },
  {
   "title": "RDS PROD",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "options": {
    "content": "db.m6g.12xlarge - CPU: **48**, Memory: **192GB**, Network: **20Gbit/s**, EBS: **13.5Gbit/s**"
   }
  },
  {
   "title": "Redis PROD",
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "cache.m6g.large - CPU: 2, Memory: **6.38 GB**, Network: **Up to 10 Gbit/s**, Nodes: **4**"
   }
  },
  { "title": "Prod EC2 Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 } },
  { "title": "Prod RDS Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 } },
  { "title": "Prod Redis Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 } },
  {
   "title": "EC2 CPUUtilization: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS CPUUtilization: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPUUtilization: Maximum per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "0001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "0001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "0001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "0001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "EC2 Traffic + CPU: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS DatabaseConnections: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DatabaseMemoryUsagePercentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EC2 NetworkIn + NetworkOut: Average 5min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS FreeableMemory: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CurrItems (& CurrVolatileItems): Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_all" },
     "metricName": "CurrItems",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EC2 NetworkPackets In & Out without Redis: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS NetworkTransmitThroughput: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkBandwidthAllowanceExceeded In & Out: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkBandwidthInAllowanceExceeded",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkBandwidthOutAllowanceExceeded",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkBandwidthOutAllowanceExceeded",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkBandwidthOutAllowanceExceeded",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EC2 EBSWriteBytes: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "EBSWriteBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS WriteIOPS: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CurrConnections: SUM 1 min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EC2 EBSReadBytes: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "EBSReadBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS WriteLatency: Maximum",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NewConnections: Sum 1 min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "NewConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EC2 EBSWriteOps: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "EBSWriteOps",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS WriteThroughput: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 76 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "StringBasedCmdsLatency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "StringBasedCmdsLatency",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "StringBasedCmdsLatency",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "StringBasedCmdsLatency",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "StringBasedCmdsLatency",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EC2 EBSReadOps: Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instance_id" },
     "metricName": "EBSReadOps",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS BinLogDiskUsage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 87 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "BinLogDiskUsage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesUsedForCache: Sum 1 min",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 87 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "BytesUsedForCache",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Lambda", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 98 } },
  {
   "title": "RDS Read/WriteLatency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 98 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ReplicationLag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "metricName": "ReplicationLag",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda: nginx-access - Error count rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$nginx_access" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda: nginx-error- Error count rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$nginx_error" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS ReadThroughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 109 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheHits: Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda: cwl - Error count rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 117 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$cwl" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CacheMisses: Sum 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 117 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "RDS WriteThroughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 120 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lamda sending logs Duration: nginx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 126 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$nginx_access" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "FunctionName": "$nginx_error" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkBytesIn: SUM per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 126 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001" },
     "metricName": "NetworkBytesIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "RDS NetworkReceiveThroughput + NetworkTransmitThroughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 131 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkBytesOut: SUM per 1 min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 135 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001" },
     "metricName": "NetworkBytesOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lamda sending logs Duration: cwl",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 136 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$cwl" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RDS FreeStorageSpace: Minimum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 141 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$rds_id" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Minimum"
    }
   ]
  },
  {
   "title": "s3 mdnbucket001 total bucket size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "BucketName": "mdnbucket001" },
     "metricName": "BucketSizeBytes",
     "namespace": "AWS/S3",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkPacketsIn: Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 145 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda: nginx - Invocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 146 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$nginx_access" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "$nginx_error" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "NetworkPacketsOut: Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 154 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda: cwl - Invocations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 155 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$cwl" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "FreeableMemory: Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 163 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "$redis_0001_001", "CacheNodeId": "$redis_all" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0002_001", "CacheNodeId": "$redis_all" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0003_001", "CacheNodeId": "$redis_all" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "$redis_0004_001", "CacheNodeId": "$redis_all" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda: nginx - Concurrent executions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 165 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$nginx_access" },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "FunctionName": "$nginx_error" },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda: cwl -Concurrent executions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 174 },
   "targets": [
    {
     "dimensions": { "FunctionName": "$cwl" },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}