{
 "title": "PHP-FPM monitoring",
 "description": "PHP-FPM aggregated data for multiple pools.",
 "tags": [ "php-fpm" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Server:",
    "query": {
     "query": "label_values(php_fpm_accepted_connections_total, job)"
    }
   },
   {
    "name": "Host",
    "query": {
     "query": "label_values(php_fpm_accepted_connections_total, instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Interval", "label": "Time Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "Pool",
    "label": "Pool",
    "query": {
     "query": "label_values(php_fpm_accepted_connections_total, socket_path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PHP FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(php_fpm_up{job=~\"^$job$\", socket_path=~\"^$Pool$\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "description": "Active processes (the number of active processes) / Max active processes (the maximum number of active processes since FPM has started)",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "php_fpm_active_processes{job=~\"^$job$\"} / php_fpm_max_active_processes{job=~\"^$job$\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(php_fpm_start_time_seconds{job=~\"$job\", socket_path=~\"$Pool\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Accepted Connections Rate",
   "type": "timeseries",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(php_fpm_accepted_connections_total{job=~\"$job\"} [$Interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Max active processes",
   "type": "timeseries",
   "description": "The maximum number of active processes since FPM has started.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "php_fpm_max_active_processes{job=~\"^$job$\"}",
     "legendFormat": "{{ job }} "
    }
   ]
  },
  {
   "title": "Active processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "php_fpm_active_processes{job=~\"^$job$\"}",
     "legendFormat": "{{ job }} "
    }
   ]
  },
  {
   "title": "Idle processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "php_fpm_idle_processes{job=~\"^$job$\"}",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Max children reached",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_max_children_reached{job=~\"^$job$\"} )",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Listen Queue",
   "type": "timeseries",
   "description": "The number of request in the queue of pending connections.",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_listen_queue{job=~\"$job$\"} [$Interval]))",
     "legendFormat": "{{socket_path }} "
    }
   ]
  },
  {
   "title": "Slow Requests Rate",
   "type": "timeseries",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_slow_requests{job=~\"$job\"} [$Interval]))",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Listen Queue Lengtht",
   "type": "timeseries",
   "description": "The size of the socket queue of pending connections.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_listen_queue_length{job=~\"$job$\"} [$Interval]))",
     "legendFormat": "{{socket_path }}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } }
 ]
}